### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by oleghnidets** [ayoy/fastlane-plugin-dropbox#2]
I provided authorization token but it gives an error:
```
 {"error_description": "code doesn't exist or has expired", "error": "invalid_grant"}
```

Can you help me please?

**Comment by ayoy** [comment]
Hi, are you using `Full Dropbox` permission type for your app? Check it in "My apps" in Dropbox.

**Comment by oleghnidets** [comment]
Yes, I use `Permission type: Full Dropbox`.

**Comment by ayoy** [comment]
I don't think I can help here, it looks like a problem with your Dropbox app or Dropbox oauth. I have just tested authorization and it works fine here.

<img width="994" alt="screen shot 2018-01-12 at 12 06 08" src="https://user-images.githubusercontent.com/14022/34872533-786f18e2-f791-11e7-8e5b-2c2642c124d8.png">

**Comment by oleghnidets** [comment]
Got it. Thanks anyway :)

**Comment by pranay1494** [comment]
i am having a similar issue can you please provide the solution.

**Comment by ayoy** [comment]
@pranay1494 the keychain password is your MacOS login password (by default, when login keychain is used).

**Comment by pranay1494** [comment]
yeah got that but can you help me with above mentioned issue?

**Comment by aadeshmindtickle** [comment]
Hello @ayoy  I am getting the same error whenever the script is asking for the authorization code: I pass the generated authorization code by app console and receives this error:

Error during authorization with Dropbox: 400 - {"error_description": "code doesn't exist or has expired", "error": "invalid_grant"}


App's permission type: Full drop box.

Any help is much appreciated!

**Comment by ya-samadi** [comment]
Please, someone find a solution for this problem ?
