### ISSUE TITLE
Unable to upload file to Dropbox

### ISSUE THREAD

**Issue by rishu-s** [ayoy/fastlane-plugin-dropbox#6]
The plugin is successfully installed. While executing the fastlane, it is throwing error "No such file or directory - security default-keychain"

**Comment by ayoy** [comment]
Are you running it on MacOS?

**Comment by rishu-s** [comment]
Running it on Windows

**Comment by ayoy** [comment]
Unfortunately, it only supports MacOS as the host system. Sorry for that. Will update docs to state that clearly.

**Comment by rishu-s** [comment]
ok, thanks for the update.

**Comment by rishu-s** [comment]
Is this plugin supported to upload APK

**Comment by ayoy** [comment]
This plugin is capable of uploading any kind of file to Drobpox.

**Comment by rishu-s** [comment]
ok. thanks
